build-search-data.js, src/theme/SearchBar/lib/lunar-search.js
Hi,
First of all, thanks for this great project!
Docusaurus has the ability to add keywords, so these can be used for search engines.
https://v2.docusaurus.io/docs/markdown-features#markdown-headers
This PR changes the build-search-data to add these keywords in the index JSON (if any), and changes the search function to also search on keywords. I am not sure about the Lunr boost score however.
Feedback is welcome.
=> Add search on keywords

src/index.js
I don't know why I didn't do it right away. This change has accelerated the indexing of my documentation by another 1.5 seconds.
=> Reduced thread pool size to the number of logical cores.

src/html-to-doc.js
Got same error as in issue #25 
Exception happens when building docusaurus and there are h2/h3 titles.
Here is a quick fix to prevent exception, if `select` returns undefined.
=> Fix for TypeError: Cannot read property 'properties' of null #25

package-lock.json, package.json
This PR fixes the peerDependency issue in NPM 7.x:
=> chore(package.json): updating @docusaurus/core version

src/utils.js
fix #47
ref.
https://github.com/MihaiValentin/lunr-languages/blob/a62fec97fb1a62bb4581c9b69a5ddedf62f8f62f/lunr.ja.js#L86
For the ja language on the `lunr-language` side, it is assumed that the `lunr` object has `TinySegmenter`. So, load `tinyseg` when language is ja.
=> fix: lunr.TinySegmenter of lang ja #47

src/index.js, src/theme/SearchBar/index.js
Thanks for this plugin! I think it's great!
I noticed that the browser can cache the `search-doc.json` and `lunr-index.json` files, causing problems presumably when they don't match each other. This results in a broken experience when what you type returns the wrong results, and highlights incorrect parts of the results.
Example:
So I've fixed it by generating a unique id (just a millisecond timestamp) for each build of the site, and including this id in the file names. This way, a given instance of the site will always request the version of these files that match - whether they are cached or not, the correct one will be received.
---
To avoid breaking compatibility with sites that have already swizzled the SearchBar component, I've left it still generating the non-uniquely named files, …
=> Fix browser cache inconsistency issue

package.json
Our build system hates peer dependencies that are out of range
=> Allowing React 17

src/theme/SearchBar/index.js
I've noticed that on slow internet connections, or when the search index is large, there's a bug.
Currently the search index is loaded when you hover over the search bar.
You can still type while it's loading, and then when the request completes, the search bar re-renders and you lose focus, which is really disruptive. You then have to modify the query a bit to get the results to show.
Here's a video demonstrating the issue when adding the plugin to the official docusaurus site, and with speed throttling on: https://vimeo.com/575802281
I'm attaching the fix that I have been using for this, though I'm aware you may not want to do this. The correct fix is probably better state management / avoiding re-renders, but tbh, I'm not sure where that problem lies.
The way this fix works is by …
=> Load search index on initial render

src/theme/SearchBar/index.js, src/theme/SearchBar/lib/DocSearch.js, src/theme/SearchBar/lib/lunar-search.js
I stumbled upon a problem with opening search suggestions in a new tab when one of the pages is opened. When I tried to open one I was getting the "Page not found" error. The issue can be reproduced in your own demo. Like this:
https://user-images.githubusercontent.com/21964985/143767162-d253690c-c613-4027-a5a3-06a6f29c4096.mp4
It happens because the suggestion's URL is relative and it's appended in the end of the current URL. So instead of opening `/docusaurus-lunr-search-multilang/docs/doc1` it opens `/docusaurus-lunr-search-multilang/docs/doc1/docs/doc2`.
Prepending the `baseUrl` from Docusaurus's config in the `LunrSearchAdapter.getHit()` method solves this issue. I already applied the same changes to my own website on a swizzled component.
=> Absolute suggestions URLs

src/theme/SearchBar/index.js, src/utils.js
Due to https://github.com/facebook/docusaurus/pull/5349, SearchBar is no longer fetching the index file on initialization because isClient has been removed.
There seems to have been a second change for the output files of the production builds so instead of `/foo/index.html`, they are now `/foo.html`. This PR updates the file scanning logic to account for that.
=> Fix indexing not working and SearchBar not working after some backwards-incompatible docusaurus changes

src/__tests__/utils.spec.js, src/utils.js
When using the `trailingSlash` option with `true` value, Docusaurus will generate `index.html` files for each page. 
This change makes sure such pages will be indexed by Lunr.
Addresses remaining issue for https://github.com/praveenn77/docusaurus-lunr-search/issues/77
=> Support trailingSlash option in docusaurus.config.js

src/utils.js
The following assumes a default `--out-dir` of `build`.
Assume a single file: `docs/intro.md`. when building with docusaurus 2.0, you get `build/docs/intro/index.html`
When you use `/` as the baseUrl, which is the default, the previous code works correctly.
When you use `/some-thing/` as the base url, your docs are still written to `build`, yet the `route` received will be: `/some-thing/docs/intro/index.html`. This route, appended with the outputDir will result in `build/some-thing/docs/intro/index.html` which does not exist.
This PR changes the path to look at depending on the baseUrl. If the default is used (`/`), then we use the route as is, otherwise, we drop the baseUrl from the `route` via substring.
-----
To reproduce,
1. follow the quickstart guide for docusaurus.
2. install lunr …
=> Files not found when baseUrl is not `/`

src/theme/SearchBar/lunar-search.js
say we got doc.url = /docs/intro.html
with baseUrl = '/', the condition failed because doc.url starts with a `/`, so we returned `doc.url
with baseUrl = `/some-thing/`, the condition succeeds because baseUrl is not `/`, so we return the concatenated url, but it's wrong. it gives: `/some-thing//docs/intro.html`
The thing is that the doc.url already contains the baseUrl, so there is no need to concatenate.
Again running off the docusaurus getting started and applying the fix locally:
`baseUrl = /`:
`baseUrl = /some-thing/`:
This is a follow up to https://github.com/praveenn77/docusaurus-lunr-search/pull/89 and https://github.com/praveenn77/docusaurus-lunr-search/pull/88
=> Avoid adding extra `/` on hits

package-lock.json, package.json, src/theme/SearchBar/index.js
I've replaced `classnames` library with `clsx`
- docusaurus uses clsx: https://github.com/facebook/docusaurus/pull/2895
- as mentioned [here](https://github.com/facebook/docusaurus/pull/2895) - it is smaller and faster
=> Replace classnames with clsx

.prettierrc, README.md, package.json, src/html-to-doc.js
This PR aims at improving the features added in [this commit](https://github.com/praveenn77/docusaurus-lunr-search/commit/71ed505ea63274e72775bcf41e6d2a206a0aa7dc).
The initial implementation worked by indexing only the immediate children of the element that had the `data-search-children` attribute. This PR builds on top of that behavior, and now indexes all heading elements under that element with the attribute, not mattering if they are direct or indirect children (E.g. children/grandchildren).
Alongside the code that handles the main purpose of this PR, this PR contains:
* `README.md` updates.
* Auto-formatting of `README.md` table.
* Codebase version bump (now 2.4.3).
* Addition of a `.prettierrc` file to enforce more consistent styling across development environments.
* A minor …
=> Further develop the `data-search-children` functionality

src/theme/SearchBar/index.jsx
On a fresh install of the latest docusaurus (v2.4.3) and docusaurus-lunr-search (v3.0.0) the following error is thrown in non-production mode:
```jsx
TypeError: Cannot read properties of undefined (reading 'length')
at eval (webpack-internal:///./node_modules/docusaurus-lunr-search/src/theme/SearchBar/index.jsx:17:1504)
```
I believe this is caused by the changes in 426e3131d7, where in `development` mode the `searchDocFile` (from `getSearchDoc()`) is just an empty array.
=> Avoid "Cannot read properties of undefined (reading 'length')"

package-lock.json, package.json
This adds support for Docusaurus 3.0.0 by expanding the peer dependencies.
Resolves #123
=> Add support for Docusaurus 3.0.0

src/theme/SearchBar/DocSearch.js, src/theme/SearchBar/index.jsx
The standard way to trigger a search bar on websites for Mac users has become the command key (see for example tailwind.com or github.com).
This PR allows focusing the search bar with either the `ctrlKey` or the `metakey`, so both platforms are supported. It also updates the placeholder text for MacOS users to show ⌘+K instead of Ctrl+K.
Let me know if this is acceptable or if you'd like to see any changes. Thanks for your work! 🙏
=> Use ⌘ to trigger search bar for Mac users

README.md, src/theme/SearchBar/DocSearch.js, src/theme/SearchBar/index.jsx, src/theme/SearchBar/lunar-search.js
Introduce a new option `maxHits`. Before you had to go with the default `5` hits which was sometimes too few.
Now you can go with `7`.
```
[
require.resolve('docusaurus-lunr-search'),
{
maxHits: 7
}
```
=> feat: Introduce option maxHits: Show more or less than the default 5 hits when searching

.gitignore, src/html-to-doc.js
I think this may resolve issues #126 and #134. 
We observed the same behavior with imports discussed in #126. In our case, the issue was caused by the imports creating additional article elements in the compiled html files. We found during indexing, that workers search through the html files to find the first article element in each file and indexes the article element if it has an element associated with the `markdown` class. So markdown pages with imports could be skipped during indexing as the article element with the markdown class is not guaranteed to be the first article element in the compiled html file. 
This PR allows the workers to search through all articles in each html file to find the article associated the `markdown` class.
=> Fix: Index html file when multiple article elements present in file

src/index.js
When invoking `docusaurus build`, Lunr reports warnings such as:
```
Overwriting existing registered function: trimmer-zh
Overwriting existing registered function: stemmer-zh
Overwriting existing registered function: stopWordFilter-zh
Overwriting existing registered function: lunr-multi-trimmer-en-zh
```
Because these warnings are printed to STDERR, they are interpreted as errors by our build system.
Docusaurus calls the [configureWebpack](https://docusaurus.io/docs/api/plugin-methods/lifecycle-apis#configureWebpack) hook twice, once for the client and once for the server (static SSR content):
```js
plugins.forEach((plugin) => {
const { configureWebpack, configurePostCss } = plugin;
if (configurePostCss) {
clientConfig = (0, utils_2.applyConfigurePostCss)(configurePostCss.bind(plugin), …
```
=> Fix warnings about duplicate lunr.Pipeline.registerFunction() calls

README.md, src/index.js
Exposes Lunr's field attribute configuration via docusaurus config. This allows users to configure the fields that are indexed by Lunr, and their relative priority.
These fields map directly to Lunr's field configuration, and are treated opaquely, so any additional features supported by Lunr (now or in the future) can be configured via this option, without any changes to docusaurus-lunr-search.
Also added documentation for the new fields configuration option.
=> Expose Lunr field attributes to docusaurus config
